---
- name: Agregamos la llave GPG para disponer el repositorio Docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: yes 

- name: Agregamos el repositorio al Source Repo 
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable 
    state: present
