---
- name: Incluir variables para la instalacion de dependencias
  include_vars:
    file: vars/dependencies.yaml
        
- name: Configuracion de dependencias  para docker engine
  apt:
    name: '{{item.name}}'
    state: '{{item.state}}'
  loop: '{{dependencias}}'
